set(SRC_FILES
    App.cpp
    Game_objects/bloon.cpp
    Game_objects/button.cpp
    collapsible.cpp
    manager.cpp
    Game_objects/map.cpp
    path.cpp
    mortal.cpp
    uuid.cpp
    loader.cpp
    shape.cpp
    test.cpp
    )
set(INCLUDE_FILES
    App.hpp
    Game_objects/bloon.hpp
    Game_objects/button.hpp
    collapsible.hpp
    interface.hpp
    manager.hpp
    Game_objects/map.hpp
    path.hpp
    move.hpp
    mortal.hpp
    uuid.hpp
    loader.hpp
    shape.hpp
    test.hpp
)

set(TEST_FILES
)
