name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake ninja-build
    - name: Configure
      run: cmake -DCMAKE_BUILD_TYPE=Debug -B build -G Ninja
    - name: Build
      run: cmake --build build
    - name: Test
      run: cd build && ctest